name: Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: amazon-corretto@1.11
      - name: Run tests
        run: sbt test
